services:
  app:
    build:
      context: .
    container_name: tienda-eco-app
    environment:
      - PORT=3000
    volumes:
      - ./data:/app/data

  apache:
    image: httpd:2.4-alpine
    container_name: tienda-eco-apache
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./public:/usr/local/apache2/htdocs:ro

  apache2:
    image: httpd:2.4-alpine
    container_name: tienda-eco-apache-2
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./public:/usr/local/apache2/htdocs:ro

  nginx:
    image: nginx:1.27-alpine
    container_name: tienda-eco-nginx
    depends_on:
      - app
      - apache
      - apache2
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs: